Repository airbnb/visx, pull requests merged in 2019-10, with the labels that each got.

#495 typescript(vx-gradient): re-write package in TypeScript
  packages/vx-gradient/package.json
  packages/vx-gradient/src/gradients/GradientDarkgreenGreen.jsx
  packages/vx-gradient/src/gradients/GradientDarkgreenGreen.tsx
  packages/vx-gradient/src/gradients/GradientLightgreenGreen.tsx
  packages/vx-gradient/src/gradients/GradientOrangeRed.jsx
  packages/vx-gradient/src/gradients/GradientOrangeRed.tsx
  packages/vx-gradient/src/gradients/GradientPinkBlue.jsx
  packages/vx-gradient/src/gradients/GradientPinkBlue.tsx
  packages/vx-gradient/src/gradients/GradientPinkRed.jsx
  packages/vx-gradient/src/gradients/GradientPinkRed.tsx
  packages/vx-gradient/src/gradients/GradientPurpleOrange.jsx
  packages/vx-gradient/src/gradients/GradientPurpleOrange.tsx
  packages/vx-gradient/src/gradients/GradientPurpleRed.jsx
  packages/vx-gradient/src/gradients/GradientPurpleRed.tsx
  packages/vx-gradient/src/gradients/GradientPurpleTeal.jsx
  packages/vx-gradient/src/gradients/GradientPurpleTeal.tsx
  packages/vx-gradient/src/gradients/GradientSteelPurple.jsx
  packages/vx-gradient/src/gradients/GradientSteelPurple.tsx
  packages/vx-gradient/src/gradients/GradientTealBlue.jsx
  packages/vx-gradient/src/gradients/GradientTealBlue.tsx
  packages/vx-gradient/src/gradients/LinearGradient.jsx
  packages/vx-gradient/src/gradients/LinearGradient.tsx
  packages/vx-gradient/src/gradients/RadialGradient.tsx
  packages/vx-gradient/src/index.ts
  packages/vx-gradient/test/Gradients.test.tsx
  packages/vx-gradient/test/LinearGradient.test.tsx
  packages/vx-gradient/test/RadialGradient.test.tsx
Labels: typescript, 🚀enhancement

#497 typescript(vx-clip-path): re-write package in TypeScript
  packages/vx-clip-path/package.json
  packages/vx-clip-path/src/clip-paths/CircleClipPath.jsx
  packages/vx-clip-path/src/clip-paths/CircleClipPath.tsx
  packages/vx-clip-path/src/clip-paths/ClipPath.jsx
  packages/vx-clip-path/src/clip-paths/ClipPath.tsx
  packages/vx-clip-path/src/clip-paths/RectClipPath.jsx
  packages/vx-clip-path/src/clip-paths/RectClipPath.tsx
  packages/vx-clip-path/src/index.ts
  packages/vx-clip-path/test/ClipPaths.test.tsx
Labels: typescript, 🚀enhancement

#509 typescript(vx-bounds): re-write package in TypeScript
  packages/vx-bounds/package.json
  packages/vx-bounds/src/enhancers/withBoundingRects.tsx
  packages/vx-bounds/src/index.ts
  packages/vx-bounds/test/withBoundingRects.test.ts
Labels: :boom: breaking changes, typescript

#501 typescript(vx-curve): re-write package in TypeScript
  packages/vx-curve/package.json
  packages/vx-curve/src/index.ts
  packages/vx-curve/test/curve.test.ts
Labels: typescript, 🚀enhancement

#524 typescript(vx-hierarchy): re-write package in TypeScript
  packages/vx-demo/src/components/tiles/treemap.js
  packages/vx-demo/src/pages/treemap.js
  packages/vx-hierarchy/package.json
  packages/vx-hierarchy/src/HierarchyDefaultLink.jsx
  packages/vx-hierarchy/src/HierarchyDefaultLink.tsx
  packages/vx-hierarchy/src/HierarchyDefaultNode.jsx
  packages/vx-hierarchy/src/HierarchyDefaultNode.tsx
  packages/vx-hierarchy/src/HierarchyDefaultRectNode.tsx
  packages/vx-hierarchy/src/hierarchies/Cluster.jsx
  packages/vx-hierarchy/src/hierarchies/Cluster.tsx
  packages/vx-hierarchy/src/hierarchies/Pack.jsx
  packages/vx-hierarchy/src/hierarchies/Pack.tsx
  packages/vx-hierarchy/src/hierarchies/Partition.jsx
  packages/vx-hierarchy/src/hierarchies/Partition.tsx
  packages/vx-hierarchy/src/hierarchies/Tree.jsx
  packages/vx-hierarchy/src/hierarchies/Tree.tsx
  packages/vx-hierarchy/src/hierarchies/Treemap.jsx
  packages/vx-hierarchy/src/hierarchies/Treemap.tsx
  packages/vx-hierarchy/src/index.ts
  packages/vx-hierarchy/src/types.ts
  packages/vx-hierarchy/src/utils/setNumOrNumAccessor.ts
  packages/vx-hierarchy/test/Cluster.test.tsx
  packages/vx-hierarchy/test/Defaults.test.jsx
  packages/vx-hierarchy/test/Defaults.test.tsx
  packages/vx-hierarchy/test/Tree.test.tsx
Labels: :boom: breaking changes, typescript, 🐛bug, 🚀enhancement

#515 typescript(vx-network): re-write package in TypeScript
  packages/vx-network/package.json
  packages/vx-network/src/DefaultLink.tsx
  packages/vx-network/src/DefaultNode.tsx
  packages/vx-network/src/Graph.jsx
  packages/vx-network/src/Graph.tsx
  packages/vx-network/src/Links.jsx
  packages/vx-network/src/Links.tsx
  packages/vx-network/src/Nodes.jsx
  packages/vx-network/src/Nodes.tsx
  packages/vx-network/src/index.ts
  packages/vx-network/src/types.ts
  packages/vx-network/test/Graph.test.tsx
Labels: :boom: breaking changes, typescript, 🚀enhancement

#504 typescript(vx-tooltip): re-write package in TypeScript
  packages/vx-tooltip/package.json
  packages/vx-tooltip/src/enhancers/withTooltip.tsx
  packages/vx-tooltip/src/index.ts
  packages/vx-tooltip/src/tooltips/Tooltip.tsx
  packages/vx-tooltip/src/tooltips/TooltipWithBounds.tsx
  packages/vx-tooltip/test/Tooltip.test.tsx
  packages/vx-tooltip/test/TooltipWithBounds.test.tsx
  packages/vx-tooltip/test/withTooltip.test.ts
Labels: typescript, 🚀enhancement

#489 typescript(vx-text): Re-write package in TypeScript
  packages/vx-text/package.json
  packages/vx-text/src/Text.jsx
  packages/vx-text/src/Text.tsx
  packages/vx-text/src/index.ts
  packages/vx-text/src/util/getStringWidth.ts
  packages/vx-text/test/Text.test.tsx
  packages/vx-text/types/reduce-css-calc/index.d.ts
Labels: typescript, 🚀enhancement

#527 typescript(vx-chord): re-write package in TypeScript
  packages/vx-chord/package.json
  packages/vx-chord/src/Chord.jsx
  packages/vx-chord/src/Chord.tsx
  packages/vx-chord/src/Ribbon.jsx
  packages/vx-chord/src/Ribbon.tsx
  packages/vx-chord/src/index.ts
  packages/vx-chord/test/Chord.test.tsx
  packages/vx-chord/test/Ribbon.test.tsx
Labels: typescript, 🚀enhancement

#520 typescript(vx-heatmap): re-write package in TypeScript
  packages/vx-heatmap/package.json
  packages/vx-heatmap/src/heatmaps/HeatmapCircle.jsx
  packages/vx-heatmap/src/heatmaps/HeatmapCircle.tsx
  packages/vx-heatmap/src/heatmaps/HeatmapRect.jsx
  packages/vx-heatmap/src/heatmaps/HeatmapRect.tsx
  packages/vx-heatmap/src/index.ts
  packages/vx-heatmap/src/types.ts
  packages/vx-heatmap/test/HeatmapCircle.test.tsx
  packages/vx-heatmap/test/HeatmapRect.test.tsx
Labels: :boom: breaking changes, typescript, 🚀enhancement

#537 typescript(vx-geo): re-write packages in TypeScript
  packages/vx-geo/package.json
  packages/vx-geo/src/graticule/Graticule.jsx
  packages/vx-geo/src/graticule/Graticule.tsx
  packages/vx-geo/src/index.ts
  packages/vx-geo/src/projections/Albers.jsx
  packages/vx-geo/src/projections/Albers.tsx
  packages/vx-geo/src/projections/AlbersUsa.jsx
  packages/vx-geo/src/projections/AlbersUsa.tsx
  packages/vx-geo/src/projections/CustomProjection.jsx
  packages/vx-geo/src/projections/CustomProjection.tsx
  packages/vx-geo/src/projections/EqualEarth.jsx
  packages/vx-geo/src/projections/EqualEarth.tsx
  packages/vx-geo/src/projections/Mercator.jsx
  packages/vx-geo/src/projections/Mercator.tsx
  packages/vx-geo/src/projections/NaturalEarth.jsx
  packages/vx-geo/src/projections/NaturalEarth.tsx
  packages/vx-geo/src/projections/Orthographic.jsx
  packages/vx-geo/src/projections/Orthographic.tsx
  packages/vx-geo/src/projections/Projection.jsx
  packages/vx-geo/src/projections/Projection.tsx
  packages/vx-geo/test/Albers.test.tsx
  packages/vx-geo/test/AlbersUsa.test.tsx
  packages/vx-geo/test/CustomProjection.test.tsx
  packages/vx-geo/test/EqualEarth.test.tsx
  packages/vx-geo/test/Mercator.test.tsx
  packages/vx-geo/test/Orthographic.test.tsx
  packages/vx-geo/test/Projection.test.tsx
Labels: :boom: breaking changes, typescript, 🐛bug, 🚀enhancement

#533 typescript(vx-threshold): re-write package in TypeScript
  packages/vx-demo/src/components/tiles/threshold.js
  packages/vx-demo/src/pages/threshold.js
  packages/vx-threshold/package.json
  packages/vx-threshold/src/Threshold.jsx
  packages/vx-threshold/src/Threshold.tsx
  packages/vx-threshold/src/index.ts
  packages/vx-threshold/test/Threshold.test.tsx
Labels: :boom: breaking changes, typescript, 📝docs, 🚀enhancement

#493 typescript(vx-event): Re-write package in TypeScript
  packages/vx-event/package.json
  packages/vx-event/src/getXAndYFromEvent.ts
  packages/vx-event/src/index.ts
  packages/vx-event/src/localPoint.js
  packages/vx-event/src/localPoint.ts
  packages/vx-event/src/localPointGeneric.ts
  packages/vx-event/src/touchPoint.js
  packages/vx-event/src/touchPoint.ts
  packages/vx-event/src/typeGuards.ts
  packages/vx-event/src/types.ts
  packages/vx-event/test/localPoint.test.ts
Labels: typescript

#544 fix(network, shape, chord, bounds): Fix type exports + misc component types
  packages/vx-bounds/src/index.ts
  packages/vx-chord/src/Ribbon.tsx
  packages/vx-network/src/Graph.tsx
  packages/vx-shape/src/shapes/BarStack.tsx
  packages/vx-shape/src/shapes/LineRadial.tsx
Labels: typescript

#543 docs(Readme): Add `yarn` and `nimbus` deets
  README.md
Labels: 📝docs

#532 typescript(vx-marker): re-write package in TypeScript
  packages/vx-marker/package.json
  packages/vx-marker/src/index.ts
  packages/vx-marker/src/markers/Marker.jsx
  packages/vx-marker/src/markers/Marker.tsx
  packages/vx-marker/test/Marker.test.tsx
Labels: typescript, 🚀enhancement

#535 typescript(vx-annotation): re-write package in TypeScript
  packages/vx-annotation/package.json
  packages/vx-annotation/src/annotations/LinePathAnnotation.tsx
  packages/vx-annotation/src/index.ts
  packages/vx-annotation/test/LinePathAnnotation.test.tsx
Labels: typescript, 🐛bug, 🚀enhancement

#549 typescript(vx-mock-data): re-write packge in TypeScript
  packages/vx-heatmap/test/HeatmapCircle.test.tsx
  packages/vx-heatmap/test/HeatmapRect.test.tsx
  packages/vx-mock-data/package.json
  packages/vx-mock-data/src/generators/genBin.js
  packages/vx-mock-data/src/generators/genBin.ts
  packages/vx-mock-data/src/generators/genBins.js
  packages/vx-mock-data/src/generators/genBins.ts
  packages/vx-mock-data/src/generators/genDateValue.js
  packages/vx-mock-data/src/generators/genDateValue.ts
  packages/vx-mock-data/src/generators/genPhyllotaxis.js
  packages/vx-mock-data/src/generators/genPhyllotaxis.ts
  packages/vx-mock-data/src/generators/genRandomNormalPoints.js
  packages/vx-mock-data/src/generators/genRandomNormalPoints.ts
  packages/vx-mock-data/src/generators/genStats.ts
  packages/vx-mock-data/src/index.ts
  packages/vx-mock-data/src/mocks/appleStock.ts
  packages/vx-mock-data/src/mocks/bitcoinPrice.ts
  packages/vx-mock-data/src/mocks/browserUsage.ts
  packages/vx-mock-data/src/mocks/cityTemperature.ts
  packages/vx-mock-data/src/mocks/exoplanets.ts
  packages/vx-mock-data/src/mocks/groupDateValue.ts
  packages/vx-mock-data/src/mocks/lesMiserables.ts
  packages/vx-mock-data/src/mocks/letterFrequency.ts
  packages/vx-mock-data/src/mocks/planets.ts
  packages/vx-mock-data/src/mocks/shakespeare.ts
  packages/vx-mock-data/test/appleStock.test.ts
  packages/vx-mock-data/test/browserUsage.test.ts
  packages/vx-mock-data/test/cityTemperature.test.ts
  packages/vx-mock-data/test/genBin.test.ts
  packages/vx-mock-data/test/genBins.test.ts
  packages/vx-mock-data/test/genDateValue.test.ts
  packages/vx-mock-data/test/genPhyllotaxis.test.ts
  packages/vx-mock-data/test/genRandomNormalPoints.test.ts
  packages/vx-mock-data/test/genStats.test.ts
  packages/vx-mock-data/test/groupDateValue.test.ts
  packages/vx-mock-data/test/letterFrequency.test.ts
Labels: typescript, 🚀enhancement
