Repository airbnb/visx, pull requests merged in 2019-12, with the labels that each got.

#559 deps: upgrade nimbus + configs
  package.json
Labels: 🏠internal

#561 deprecate `@vx/boxplot`
  packages/vx-axis/test/Axis.test.jsx
  packages/vx-axis/test/AxisBottom.test.jsx
  packages/vx-axis/test/AxisLeft.test.jsx
  packages/vx-axis/test/AxisRight.test.jsx
  packages/vx-axis/test/AxisTop.test.jsx
  packages/vx-boxplot/.npmrc
  packages/vx-boxplot/Readme.md
  packages/vx-boxplot/docs/api.md
  packages/vx-boxplot/docs/description.md
  packages/vx-boxplot/docs/docs.md
  packages/vx-boxplot/docs/install.md
  packages/vx-boxplot/package.json
  packages/vx-boxplot/src/boxplots/BoxPlot.jsx
  packages/vx-boxplot/src/index.js
  packages/vx-boxplot/src/util/computeStats.js
  packages/vx-boxplot/test/BoxPlot.test.jsx
  packages/vx-demo/package.json
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/statsplot.js
  packages/vx-demo/src/pages/docs.js
  packages/vx-demo/src/pages/statsplot.js
  packages/vx-demo/src/static/docs/vx-annotation.html
  packages/vx-demo/src/static/docs/vx-axis.html
  packages/vx-demo/src/static/docs/vx-bounds.html
  packages/vx-demo/src/static/docs/vx-boxplot.html
  packages/vx-demo/src/static/docs/vx-brush.html
  packages/vx-demo/src/static/docs/vx-chord.html
  packages/vx-demo/src/static/docs/vx-clip-path.html
  packages/vx-demo/src/static/docs/vx-curve.html
  packages/vx-demo/src/static/docs/vx-demo.html
  packages/vx-demo/src/static/docs/vx-drag.html
  packages/vx-demo/src/static/docs/vx-event.html
  packages/vx-demo/src/static/docs/vx-geo.html
  packages/vx-demo/src/static/docs/vx-glyph.html
  packages/vx-demo/src/static/docs/vx-gradient.html
  packages/vx-demo/src/static/docs/vx-grid.html
  packages/vx-demo/src/static/docs/vx-group.html
  packages/vx-demo/src/static/docs/vx-heatmap.html
  packages/vx-demo/src/static/docs/vx-hierarchy.html
  packages/vx-demo/src/static/docs/vx-legend.html
  packages/vx-demo/src/static/docs/vx-marker.html
  packages/vx-demo/src/static/docs/vx-mock-data.html
  packages/vx-demo/src/static/docs/vx-network.html
  packages/vx-demo/src/static/docs/vx-pattern.html
  packages/vx-demo/src/static/docs/vx-point.html
  packages/vx-demo/src/static/docs/vx-responsive.html
  packages/vx-demo/src/static/docs/vx-scale.html
  packages/vx-demo/src/static/docs/vx-shape.html
  packages/vx-demo/src/static/docs/vx-stats.html
  packages/vx-demo/src/static/docs/vx-text.html
  packages/vx-demo/src/static/docs/vx-threshold.html
  packages/vx-demo/src/static/docs/vx-tooltip.html
  packages/vx-demo/src/static/docs/vx-voronoi.html
  packages/vx-demo/src/static/docs/vx-vx.html
  packages/vx-demo/src/static/docs/vx-zoom.html
  packages/vx-legend/test/Legend.test.jsx
  packages/vx-vx/package.json
  packages/vx-vx/src/index.js
  packages/vx-vx/test/index.test.js
Labels: :boom: breaking changes

#518 typescript(vx-glyph): re-write package in TypeScript
  packages/vx-glyph/package.json
  packages/vx-glyph/src/glyphs/Glyph.jsx
  packages/vx-glyph/src/glyphs/Glyph.tsx
  packages/vx-glyph/src/glyphs/GlyphCircle.jsx
  packages/vx-glyph/src/glyphs/GlyphCircle.tsx
  packages/vx-glyph/src/glyphs/GlyphCross.jsx
  packages/vx-glyph/src/glyphs/GlyphCross.tsx
  packages/vx-glyph/src/glyphs/GlyphDiamond.jsx
  packages/vx-glyph/src/glyphs/GlyphDiamond.tsx
  packages/vx-glyph/src/glyphs/GlyphDot.jsx
  packages/vx-glyph/src/glyphs/GlyphDot.tsx
  packages/vx-glyph/src/glyphs/GlyphSquare.jsx
  packages/vx-glyph/src/glyphs/GlyphSquare.tsx
  packages/vx-glyph/src/glyphs/GlyphStar.jsx
  packages/vx-glyph/src/glyphs/GlyphStar.tsx
  packages/vx-glyph/src/glyphs/GlyphTriangle.jsx
  packages/vx-glyph/src/glyphs/GlyphTriangle.tsx
  packages/vx-glyph/src/glyphs/GlyphWye.jsx
  packages/vx-glyph/src/glyphs/GlyphWye.tsx
  packages/vx-glyph/src/index.ts
  packages/vx-glyph/test/Circle.test.tsx
  packages/vx-glyph/test/Cross.test.tsx
  packages/vx-glyph/test/Diamond.test.tsx
  packages/vx-glyph/test/Dot.test.tsx
  packages/vx-glyph/test/Glyph.test.tsx
  packages/vx-glyph/test/Square.test.tsx
  packages/vx-glyph/test/Star.test.tsx
  packages/vx-glyph/test/Triangle.test.tsx
  packages/vx-glyph/test/Wye.test.tsx
Labels: :boom: breaking changes, typescript, 🚀enhancement

#553 [feature][vx-brush] add Brush component
  packages/vx-brush/package.json
  packages/vx-brush/src/BaseBrush.tsx
  packages/vx-brush/src/Brush.tsx
  packages/vx-brush/src/BrushCorner.tsx
  packages/vx-brush/src/BrushHandle.tsx
  packages/vx-brush/src/BrushSelection.tsx
  packages/vx-brush/src/brushes/BoxBrush.jsx
  packages/vx-brush/src/enhancers/withBrush.js
  packages/vx-brush/src/index.js
  packages/vx-brush/src/index.ts
  packages/vx-brush/src/types.ts
  packages/vx-brush/src/utils.ts
  packages/vx-brush/src/utils/constrainToRegion.js
  packages/vx-brush/src/utils/getCoordsFromEvent.js
  packages/vx-brush/test/BoxBrush.test.js
  packages/vx-brush/test/Brush.test.tsx
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/brush.js
  packages/vx-demo/src/pages/brush.js
  packages/vx-responsive/test/ScaleSVG.test.tsx
  packages/vx-vx/test/index.test.js
Labels: typescript, 🚀enhancement

#565 typescript(vx-grid): re-write package in TypeScript
  packages/vx-grid/package.json
  packages/vx-grid/src/grids/Grid.tsx
  packages/vx-grid/src/grids/GridColumns.tsx
  packages/vx-grid/src/grids/GridRows.tsx
  packages/vx-grid/src/index.ts
  packages/vx-grid/src/types.ts
  packages/vx-grid/test/Columns.test.tsx
  packages/vx-grid/test/Grid.test.tsx
  packages/vx-grid/test/Rows.test.tsx
Labels: typescript, 🚀enhancement

#567 fix(vx-brush): Fix BaseBrush, iterate on types + gallery
  packages/vx-brush/src/BaseBrush.tsx
  packages/vx-brush/src/Brush.tsx
  packages/vx-brush/src/BrushCorner.tsx
  packages/vx-brush/src/BrushHandle.tsx
  packages/vx-brush/src/BrushSelection.tsx
  packages/vx-brush/src/types.ts
  packages/vx-brush/src/utils.ts
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/brush.js
  packages/vx-demo/src/pages/brush.js
  packages/vx-drag/src/Drag.tsx
Labels: typescript, 🐛bug, 🚀enhancement

#569 typescript(vx-axis): re-write package in TypeScript
  packages/vx-axis/package.json
  packages/vx-axis/src/axis/Axis.tsx
  packages/vx-axis/src/axis/AxisBottom.jsx
  packages/vx-axis/src/axis/AxisBottom.tsx
  packages/vx-axis/src/axis/AxisLeft.tsx
  packages/vx-axis/src/axis/AxisRight.tsx
  packages/vx-axis/src/axis/AxisTop.tsx
  packages/vx-axis/src/constants/orientation.js
  packages/vx-axis/src/constants/orientation.ts
  packages/vx-axis/src/index.ts
  packages/vx-axis/src/types.ts
  packages/vx-axis/src/utils/center.js
  packages/vx-axis/src/utils/center.ts
  packages/vx-axis/src/utils/identity.js
  packages/vx-axis/src/utils/labelTransform.js
  packages/vx-axis/src/utils/labelTransform.ts
  packages/vx-axis/src/utils/toNumberOrUndefined.ts
  packages/vx-axis/src/utils/toString.ts
  packages/vx-axis/test/Axis.test.tsx
  packages/vx-axis/test/AxisBottom.test.tsx
  packages/vx-axis/test/AxisLeft.test.tsx
  packages/vx-axis/test/AxisRight.test.tsx
  packages/vx-axis/test/AxisTop.test.tsx
  packages/vx-axis/test/Orientation.test.ts
  packages/vx-axis/test/scales.test.tsx
  packages/vx-text/src/Text.tsx
Labels: typescript, 🚀enhancement

#570 typescript(vx-stats): re-write package in TypeScript
  packages/vx-stats/package.json
  packages/vx-stats/src/BoxPlot.tsx
  packages/vx-stats/src/ViolinPlot.tsx
  packages/vx-stats/src/index.js
  packages/vx-stats/src/index.ts
  packages/vx-stats/src/types.ts
  packages/vx-stats/src/util/computeStats.ts
  packages/vx-stats/src/violinplot/ViolinPlot.jsx
  packages/vx-stats/test/BoxPlot.test.tsx
  packages/vx-stats/test/ViolinPlot.test.tsx
  packages/vx-stats/test/computeStats.test.ts
Labels: :boom: breaking changes, typescript, 🚀enhancement
