Repository airbnb/visx, pull requests merged in 2019-01, with the labels that each got.

#400 [responsive][docs] add innerRef prop docs
  packages/vx-demo/static/docs/vx-responsive.html
  packages/vx-responsive/Readme.md
  packages/vx-responsive/docs/api.md
  packages/vx-responsive/docs/docs.md
Labels: 📝docs

#407 Add Equal Earth projection to @vx/geo
  packages/vx-demo/static/docs/vx-bounds.html
  packages/vx-demo/static/docs/vx-geo.html
  packages/vx-demo/static/docs/vx-mock-data.html
  packages/vx-demo/static/docs/vx-pattern.html
  packages/vx-demo/static/docs/vx-point.html
  packages/vx-demo/static/docs/vx-responsive.html
  packages/vx-demo/static/docs/vx-tooltip.html
  packages/vx-geo/Readme.md
  packages/vx-geo/docs/api.md
  packages/vx-geo/docs/docs.md
  packages/vx-geo/package.json
  packages/vx-geo/src/index.js
  packages/vx-geo/src/projections/EqualEarth.js
  packages/vx-geo/src/projections/Projection.js
  packages/vx-geo/test/EqualEarth.test.js
Labels: 🚀enhancement

#408 Fix-VX-Responsive-ScaleSVG-PropTypes
  packages/vx-responsive/docs/api.md
  packages/vx-responsive/docs/docs.md
  packages/vx-responsive/src/components/ScaleSVG.js
Labels: 🐛bug

#409 [shape/BarGroupHorizontal] Remove unnecessary destructuring of props in demo code
  packages/vx-demo/pages/bargrouphorizontal.js
Labels: 🐛bug
