Repository airbnb/visx, pull requests merged in 2020-08, with the labels that each got.

#774 feat(vx-shape): add BarRounded shape
  packages/vx-shape/src/index.ts
  packages/vx-shape/src/shapes/BarRounded.tsx
  packages/vx-shape/test/BarRounded.test.tsx
Labels: 🚀enhancement

#775 feat(grid): update scale types in vx/grid
  packages/vx-demo/src/sandboxes/vx-area/Example.tsx
  packages/vx-demo/src/sandboxes/vx-axis/Example.tsx
  packages/vx-demo/src/sandboxes/vx-barstack/Example.tsx
  packages/vx-grid/package.json
  packages/vx-grid/src/grids/Grid.tsx
  packages/vx-grid/src/grids/GridColumns.tsx
  packages/vx-grid/src/grids/GridRows.tsx
  packages/vx-grid/src/types.ts
Labels: :boom: breaking changes

#778 new(vx-shape): add SplitLinePath
  packages/vx-demo/src/components/Gallery/SplitLinePathTile.tsx
  packages/vx-demo/src/components/Gallery/index.tsx
  packages/vx-demo/src/pages/splitlinepath.tsx
  packages/vx-demo/src/sandboxes/exampleToVxDependencyLookup.ts
  packages/vx-demo/src/sandboxes/vx-shape-splitlinepath/Example.tsx
  packages/vx-demo/src/sandboxes/vx-shape-splitlinepath/generateSinPoints.ts
  packages/vx-demo/src/sandboxes/vx-shape-splitlinepath/index.tsx
  packages/vx-demo/src/sandboxes/vx-shape-splitlinepath/package.json
  packages/vx-demo/src/sandboxes/vx-shape-splitlinepath/sandbox-styles.css
  packages/vx-shape/package.json
  packages/vx-shape/src/index.ts
  packages/vx-shape/src/shapes/SplitLinePath.tsx
  packages/vx-shape/src/util/getSplitLineSegments.ts
Labels: 🐯example, 🚀enhancement

#782 new(vx-xychart): add package boilerplate
  packages/vx-demo/package.json
  packages/vx-demo/src/pages/xychart.tsx
  packages/vx-demo/src/sandboxes/vx-xychart/Example.tsx
  packages/vx-demo/src/sandboxes/vx-xychart/index.tsx
  packages/vx-demo/src/sandboxes/vx-xychart/package.json
  packages/vx-demo/src/sandboxes/vx-xychart/sandbox-styles.css
  packages/vx-xychart/README.md
  packages/vx-xychart/package.json
  packages/vx-xychart/src/components/XYChart.tsx
  packages/vx-xychart/src/index.ts
Labels: 🚀enhancement

#783 feat(vx-marker): add markers
  packages/vx-demo/src/sandboxes/vx-curve/Example.tsx
  packages/vx-demo/src/sandboxes/vx-curve/package.json
  packages/vx-marker/Readme.md
  packages/vx-marker/src/index.ts
  packages/vx-marker/src/markers/Arrow.tsx
  packages/vx-marker/src/markers/Circle.tsx
  packages/vx-marker/src/markers/Cross.tsx
  packages/vx-marker/src/markers/Line.tsx
  packages/vx-marker/src/markers/Marker.tsx
  packages/vx-marker/src/markers/X.tsx
  packages/vx-marker/test/Arrow.test.tsx
  packages/vx-marker/test/Circle.test.tsx
  packages/vx-marker/test/Cross.test.tsx
  packages/vx-marker/test/Line.test.tsx
  packages/vx-marker/test/X.test.tsx
Labels: :boom: breaking changes, 🚀enhancement

#784 test: increase code coverage
  package.json
  packages/vx-annotation/test/LinePathAnnotation.test.tsx
  packages/vx-bounds/test/withBoundingRects.test.ts
  packages/vx-bounds/test/withBoundingRects.test.tsx
Labels: 🏠internal

#785 new(xychart): add themes + ThemeProvider
  packages/vx-demo/src/sandboxes/vx-xychart/Controls.tsx
  packages/vx-demo/src/sandboxes/vx-xychart/Example.tsx
  packages/vx-demo/src/sandboxes/vx-xychart/customTheme.ts
  packages/vx-xychart/src/components/XYChart.tsx
  packages/vx-xychart/src/context/ThemeContext.tsx
  packages/vx-xychart/src/index.ts
  packages/vx-xychart/src/providers/ThemeProvider.tsx
  packages/vx-xychart/src/theme/buildChartTheme.ts
  packages/vx-xychart/src/theme/colors.ts
  packages/vx-xychart/src/theme/themes/dark.ts
  packages/vx-xychart/src/theme/themes/light.ts
  packages/vx-xychart/src/types/index.ts
  packages/vx-xychart/src/types/theme.ts
  packages/vx-xychart/test/theme.test.tsx
Labels: 🚀enhancement
