Repository airbnb/visx, pull requests merged in 2020-02, with the labels that each got.

#621 fix(vx-responsive): fix enhancer parent/screen size checks
  packages/vx-responsive/src/enhancers/withParentSize.tsx
  packages/vx-responsive/src/enhancers/withScreenSize.tsx
Labels: 🐛bug

#578 Fixed Zoom constrain prop to work with useCallback made functions
  packages/vx-zoom/src/Zoom.tsx
Labels: 🐛bug

#610 Allow withTooltip to be used to enhance components rendered within an SVG element
  packages/vx-tooltip/Readme.md
  packages/vx-tooltip/src/enhancers/withTooltip.tsx
  packages/vx-tooltip/test/withTooltip.test.ts
  packages/vx-tooltip/test/withTooltip.test.tsx
Labels: 🚀enhancement

#631 Add useTooltip hook
  packages/vx-demo/src/components/tiles/BarStack.tsx
  packages/vx-demo/src/pages/BarStack.tsx
  packages/vx-tooltip/Readme.md
  packages/vx-tooltip/package.json
  packages/vx-tooltip/src/enhancers/withTooltip.tsx
  packages/vx-tooltip/src/hooks/useTooltip.ts
  packages/vx-tooltip/src/index.ts
  packages/vx-tooltip/test/useTooltip.test.tsx
Labels: :boom: breaking changes, 🏠internal, 📝docs, 🚀enhancement
