Repository airbnb/visx, pull requests merged in 2020-01, with the labels that each got.

#551 typescript(vx-legend): re-write package in TypeScript
  package.json
  packages/vx-legend/package.json
  packages/vx-legend/src/index.ts
  packages/vx-legend/src/legends/Legend.jsx
  packages/vx-legend/src/legends/Legend/LegendItem.tsx
  packages/vx-legend/src/legends/Legend/LegendLabel.tsx
  packages/vx-legend/src/legends/Legend/LegendShape.tsx
  packages/vx-legend/src/legends/Legend/index.tsx
  packages/vx-legend/src/legends/LegendShape.jsx
  packages/vx-legend/src/legends/Linear.jsx
  packages/vx-legend/src/legends/Linear.tsx
  packages/vx-legend/src/legends/Ordinal.jsx
  packages/vx-legend/src/legends/Ordinal.tsx
  packages/vx-legend/src/legends/Quantile.jsx
  packages/vx-legend/src/legends/Quantile.tsx
  packages/vx-legend/src/legends/Size.jsx
  packages/vx-legend/src/legends/Size.tsx
  packages/vx-legend/src/legends/Threshold.jsx
  packages/vx-legend/src/legends/Threshold.tsx
  packages/vx-legend/src/shapes/Circle.jsx
  packages/vx-legend/src/shapes/Circle.tsx
  packages/vx-legend/src/shapes/Rect.jsx
  packages/vx-legend/src/shapes/Rect.tsx
  packages/vx-legend/src/types/index.ts
  packages/vx-legend/src/util/labelTransformFactory.ts
  packages/vx-legend/src/util/renderShape.js
  packages/vx-legend/src/util/renderShape.ts
  packages/vx-legend/src/util/valueOrIdentity.js
  packages/vx-legend/src/util/valueOrIdentity.ts
  packages/vx-legend/test/Legend.test.tsx
  packages/vx-legend/test/LegendLinear.test.tsx
  packages/vx-legend/test/LegendOrdinal.test.tsx
  packages/vx-legend/test/LegendQuantile.test.tsx
  packages/vx-legend/test/LegendSize.test.tsx
  packages/vx-legend/test/LegendThreshold.test.tsx
  packages/vx-legend/test/scales.test.tsx
  packages/vx-scale/src/scales/band.ts
Labels: :boom: breaking changes, typescript, 🚀enhancement

#574 Update Chord Diagram example to make more sense
  packages/vx-demo/src/components/tiles/chord.js
  packages/vx-demo/src/pages/chord.js
Labels: 🐯example

#584 typescript(vx-demo): rewrite StatsPlot example in TypeScript
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Statsplot.tsx
  packages/vx-demo/src/pages/Statsplot.tsx
  packages/vx-responsive/src/enhancers/withParentSize.tsx
  packages/vx-responsive/src/enhancers/withScreenSize.tsx
  packages/vx-scale/src/scales/band.ts
  packages/vx-stats/src/types.ts
  packages/vx-tooltip/src/enhancers/withTooltip.tsx
Labels: 🐛bug, 📝docs, 🤖 typescript

#582 typescript(vx-demo): re-write Chord demo in TypeScript
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Chord.tsx
  packages/vx-demo/src/pages/Chord.tsx
  packages/vx-demo/src/pages/chord.js
  packages/vx-legend/src/legends/Ordinal.tsx
  packages/vx-legend/test/scales.test.tsx
  packages/vx-scale/src/scales/ordinal.ts
Labels: 🐛bug, 📝docs, 🤖 typescript

#592 typescript(vx-demo): rewrite Dots + Streamgraph examples in TypeScript
  packages/vx-demo/package.json
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Dots.tsx
  packages/vx-demo/src/components/tiles/Streamgraph.tsx
  packages/vx-demo/src/components/tiles/dots.js
  packages/vx-demo/src/components/tiles/streamgraph.js
  packages/vx-demo/src/pages/Dots.tsx
  packages/vx-demo/src/pages/Streamgraph.tsx
  packages/vx-demo/src/pages/dots.js
  packages/vx-demo/src/pages/streamgraph.js
  packages/vx-shape/src/shapes/Stack.tsx
Labels: 📝docs, 🚀enhancement, 🤖 typescript

#593 typescript(vx-demo): rewrite Bars, BarGroup, BarGroupHorizontal, BarStack, BarStackHorizontal, and Area Stack in TypeScript
  package.json
  packages/vx-axis/src/types.ts
  packages/vx-demo/package.json
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/BarGroup.tsx
  packages/vx-demo/src/components/tiles/BarGroupHorizontal.tsx
  packages/vx-demo/src/components/tiles/BarStack.tsx
  packages/vx-demo/src/components/tiles/BarStackHorizontal.tsx
  packages/vx-demo/src/components/tiles/Bars.tsx
  packages/vx-demo/src/components/tiles/Stacked-Areas.tsx
  packages/vx-demo/src/components/tiles/bargroup.js
  packages/vx-demo/src/components/tiles/bargrouphorizontal.js
  packages/vx-demo/src/components/tiles/barstack.js
  packages/vx-demo/src/components/tiles/barstackhorizontal.js
  packages/vx-demo/src/components/tiles/stacked.js
  packages/vx-demo/src/pages/BarGroup.tsx
  packages/vx-demo/src/pages/BarGroupHorizontal.tsx
  packages/vx-demo/src/pages/BarStack.tsx
  packages/vx-demo/src/pages/BarStackHorizontal.tsx
  packages/vx-demo/src/pages/Bars.tsx
  packages/vx-demo/src/pages/Stacked-Areas.tsx
  packages/vx-demo/src/pages/bargroup.js
  packages/vx-demo/src/pages/bargrouphorizontal.js
  packages/vx-demo/src/pages/barstack.js
  packages/vx-demo/src/pages/barstackhorizontal.js
  packages/vx-demo/src/pages/stacked-areas.js
  packages/vx-grid/src/grids/Grid.tsx
  packages/vx-grid/src/grids/GridColumns.tsx
  packages/vx-grid/src/grids/GridRows.tsx
  packages/vx-grid/src/types.ts
  packages/vx-shape/src/shapes/AreaStack.tsx
  packages/vx-shape/src/shapes/BarGroup.tsx
  packages/vx-shape/src/shapes/BarGroupHorizontal.tsx
  packages/vx-shape/src/shapes/BarStack.tsx
  packages/vx-shape/src/shapes/BarStackHorizontal.tsx
  packages/vx-shape/src/shapes/Stack.tsx
  packages/vx-shape/src/types.ts
  packages/vx-shape/test/BarGroup.test.tsx
  packages/vx-shape/test/BarGroupHorizontal.test.tsx
  packages/vx-shape/test/BarStack.test.tsx
  packages/vx-shape/test/BarStackHorizontal.test.tsx
Labels: 🐛bug, 📝docs, 🤖 typescript

#580 typescript(vx-demo): re-write voronoi demo in TypeScript
  packages/vx-demo/src/components/charts/VoronoiChart.js
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Voronoi.tsx
  packages/vx-demo/src/components/tiles/voronoi.js
  packages/vx-demo/src/pages/Voronoi.tsx
  packages/vx-demo/src/pages/voronoi.js
Labels: 📝docs, 🤖 typescript

#594 typescript(vx-demo): rewrite LinkTypes example in TypeScript
  package.json
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/LinkTypes.tsx
  packages/vx-demo/src/components/tiles/linkTypes.js
  packages/vx-demo/src/pages/LinkTypes.tsx
  packages/vx-demo/src/pages/linkTypes.js
Labels: 📝docs, 🤖 typescript

#589 typescript(vx-demo): rewrite Treemap + Trees examples in TypeScript
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Treemap.tsx
  packages/vx-demo/src/components/tiles/Trees.tsx
  packages/vx-demo/src/components/tiles/treemap.js
  packages/vx-demo/src/pages/Treemap.tsx
  packages/vx-demo/src/pages/Trees.tsx
  packages/vx-demo/src/pages/treemap.js
  packages/vx-hierarchy/src/hierarchies/Treemap.tsx
  packages/vx-hierarchy/src/types.ts
Labels: 📝docs, 🚀enhancement, 🤖 typescript

#595 typescript(vx-demo): rewrite Areas + Axis examples in TypeScript
  packages/vx-axis/src/axis/Axis.tsx
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Areas.tsx
  packages/vx-demo/src/components/tiles/Axis.tsx
  packages/vx-demo/src/pages/Areas.tsx
  packages/vx-demo/src/pages/Axis.tsx
  packages/vx-demo/src/pages/areas.js
Labels: 📝docs, 🤖 typescript

#581 typescript(vx-demo): re-write Responsive + Lines demos in TypeScript
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Lines.tsx
  packages/vx-demo/src/components/tiles/Responsive.tsx
  packages/vx-demo/src/components/tiles/lines.js
  packages/vx-demo/src/components/tiles/responsive.js
  packages/vx-demo/src/pages/Lines.tsx
  packages/vx-demo/src/pages/Responsive.tsx
  packages/vx-demo/src/pages/lines.js
  packages/vx-demo/src/pages/responsive.js
Labels: 📝docs, 🤖 typescript

#596 typescript(vx-demo): rewrite Dendrograms + Zoom examples in TypeScript
  packages/vx-demo/package.json
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Dendrograms.tsx
  packages/vx-demo/src/components/tiles/Zoom-i.tsx
  packages/vx-demo/src/components/tiles/zoom-i.js
  packages/vx-demo/src/pages/Dendrograms.tsx
  packages/vx-demo/src/pages/Zoom-i.tsx
  packages/vx-demo/src/pages/zoom-i.js
  packages/vx-zoom/src/Zoom.tsx
  packages/vx-zoom/src/types.ts
Labels: 🐛bug, 📝docs, 🤖 typescript

#597 typescript(vx-demo): rewrite Threshold + Text examples in TypeScript
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Threshold.tsx
  packages/vx-demo/src/pages/Text.tsx
  packages/vx-demo/src/pages/Threshold.tsx
  packages/vx-demo/src/pages/text.js
  packages/vx-threshold/src/Threshold.tsx
Labels: 🐛bug, 📝docs, 🤖 typescript

#585 typescript(vx-demo): rewrite Geo examples in TypeScript
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Geo-Custom.tsx
  packages/vx-demo/src/components/tiles/Geo-Mercator.tsx
  packages/vx-demo/src/components/tiles/geo-custom.js
  packages/vx-demo/src/components/tiles/geo-mercator.js
  packages/vx-demo/src/pages/Geo-Custom.tsx
  packages/vx-demo/src/pages/Geo-Mercator.tsx
  packages/vx-demo/src/pages/geo-custom.js
  packages/vx-demo/src/pages/geo-mercator.js
  packages/vx-geo/src/projections/Albers.tsx
  packages/vx-geo/src/projections/AlbersUsa.tsx
  packages/vx-geo/src/projections/CustomProjection.tsx
  packages/vx-geo/src/projections/EqualEarth.tsx
  packages/vx-geo/src/projections/Mercator.tsx
  packages/vx-geo/src/projections/NaturalEarth.tsx
  packages/vx-geo/src/projections/Orthographic.tsx
  packages/vx-geo/src/projections/Projection.tsx
  packages/vx-geo/src/types.ts
Labels: 📝docs, 🤖 typescript

#586 typescript(vx-demo): rewrite Heatmap + Pies examples in TypeScript
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Heatmap.tsx
  packages/vx-demo/src/components/tiles/Pies.tsx
  packages/vx-demo/src/components/tiles/heatmap.js
  packages/vx-demo/src/pages/Heatmaps.tsx
  packages/vx-demo/src/pages/Pies.tsx
  packages/vx-demo/src/pages/heatmaps.js
  packages/vx-heatmap/src/heatmaps/HeatmapCircle.tsx
  packages/vx-heatmap/src/heatmaps/HeatmapRect.tsx
  packages/vx-heatmap/src/types.ts
  packages/vx-mock-data/src/generators/genBins.ts
Labels: 📝docs, 🚀enhancement, 🤖 typescript

#598 typescript(vx-demo): rewrite Brush demo in TypeScript
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Brush.tsx
  packages/vx-demo/src/pages/Brush.tsx
  packages/vx-shape/src/types.ts
  packages/vx-shape/test/AreaClosed.test.tsx
  packages/vx-shape/test/BarGroup.test.tsx
  packages/vx-shape/test/BarGroupHorizontal.test.tsx
  packages/vx-shape/test/BarStack.test.tsx
  packages/vx-shape/test/BarStackHorizontal.test.tsx
Labels: 📝docs, 🤖 typescript

#599 typescript(vx-demo): rewrite Drag-i and Drag-ii demos in TypeScript
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Drag-i.tsx
  packages/vx-demo/src/components/tiles/Drag-ii.tsx
  packages/vx-demo/src/components/tiles/Geo-Mercator.tsx
  packages/vx-demo/src/components/tiles/drag-i.js
  packages/vx-demo/src/components/tiles/drag-ii.js
  packages/vx-demo/src/next.config.js
  packages/vx-demo/src/pages/Drag-i.tsx
  packages/vx-demo/src/pages/Drag-ii.tsx
  packages/vx-demo/src/pages/drag-i.js
  packages/vx-demo/src/pages/drag-ii.js
  packages/vx-demo/src/types/index.ts
  packages/vx-drag/src/Drag.tsx
  packages/vx-event/src/localPoint.ts
  packages/vx-event/src/localPointGeneric.ts
Labels: 🐛bug, 📝docs, 🤖 typescript

#587 typescript(vx-demo): rewrite Legends example in TypeScript
  packages/vx-demo/package.json
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Legends.tsx
  packages/vx-demo/src/pages/Legends.tsx
  packages/vx-demo/src/pages/legends.js
Labels: 📝docs, 🤖 typescript

#590 typescript(vx-demo): rewrite Glyphs + LineRadial + Radar examples in TypeScript
  packages/vx-demo/src/components/gallery.js
  packages/vx-demo/src/components/tiles/Glyphs.tsx
  packages/vx-demo/src/components/tiles/LineRadial.tsx
  packages/vx-demo/src/components/tiles/Radar.tsx
  packages/vx-demo/src/pages/Glyphs.tsx
  packages/vx-demo/src/pages/LineRadial.tsx
  packages/vx-demo/src/pages/Radar.tsx
  packages/vx-demo/src/pages/radar.js
Labels: 📝docs, 🤖 typescript

#612 fix(vx-legend): Fix label generation in `Threshold` legend
  packages/vx-demo/src/components/tiles/Legends.tsx
  packages/vx-demo/src/pages/Legends.tsx
  packages/vx-legend/src/legends/Linear.tsx
  packages/vx-legend/src/legends/Threshold.tsx
Labels: 🐛bug, 🤖 typescript

#606 Migrate SimpleBar example to typescript
  packages/vx-demo/src/components/charts/SimpleBar.tsx
  packages/vx-demo/src/components/codeblocks/SimpleBarCode.js
  packages/vx-demo/src/static/docs/vx-scale.html
  packages/vx-scale/Readme.md
Labels: 📝docs, 🚀enhancement

#615 new(vx-scale) add scaleSqrt
  packages/vx-scale/Readme.md
  packages/vx-scale/src/index.ts
  packages/vx-scale/src/scales/squareRoot.ts
  packages/vx-scale/test/scaleSqrt.test.ts
Labels: 📝docs, 🚀enhancement

#614 feat(vx-brush): adds resetOnEnd property
  packages/vx-brush/src/BaseBrush.tsx
  packages/vx-brush/src/Brush.tsx
Labels: 🚀enhancement
