Repository airbnb/visx, pull requests merged in 2020-06, with the labels that each got.

#558 Fix debounced calls after unmount in responsive components
  packages/vx-responsive/src/components/ParentSize.tsx
  packages/vx-responsive/src/enhancers/withParentSize.tsx
  packages/vx-responsive/src/enhancers/withScreenSize.tsx
Labels: 🐛bug

#748 internal(demo): static export deploys
  packages/vx-demo/.gitignore
  packages/vx-demo/next.config.js
  packages/vx-demo/package.json
  packages/vx-demo/public/static/doc_styles.css
  packages/vx-demo/public/static/docs/vx-demo.html
  packages/vx-demo/public/static/favicon.ico
  packages/vx-demo/public/static/logo-dark.png
  packages/vx-demo/public/static/prism/prism-funky.css
  packages/vx-demo/public/static/prism/prism-line-numbers.css
  packages/vx-demo/public/static/style.css
  packages/vx-demo/public/static/tiger-gray.png
  packages/vx-demo/public/static/tiger-twitter-card.jpg
  packages/vx-demo/public/static/tiger.png
  packages/vx-demo/public/static/vx-gallery.png
  packages/vx-demo/public/static/vx-geo/world-topo.json
  packages/vx-demo/vercel.json
Labels: 🏠internal

#751 fix(vx-responsive): fix debounce types
  packages/vx-responsive/src/components/ParentSize.tsx
  packages/vx-responsive/src/enhancers/withParentSize.tsx
  packages/vx-responsive/src/enhancers/withScreenSize.tsx
Labels: 🐛bug

#744 add diagonal right to left pattern
  packages/vx-demo/src/sandboxes/vx-pattern/Example.tsx
  packages/vx-pattern/src/constants/index.ts
  packages/vx-pattern/src/patterns/Lines.tsx
  packages/vx-pattern/test/PatternLines.test.tsx
Labels: 🚀enhancement

#749 new(vx-legend): add Line, legendLabelProps, more props in renderShape
  packages/vx-legend/src/legends/Legend/LegendLabel.tsx
  packages/vx-legend/src/legends/Legend/LegendShape.tsx
  packages/vx-legend/src/legends/Legend/index.tsx
  packages/vx-legend/src/shapes/Circle.tsx
  packages/vx-legend/src/shapes/Line.tsx
  packages/vx-legend/src/types/index.ts
  packages/vx-legend/src/util/renderShape.ts
  packages/vx-legend/test/Legend.test.tsx
Labels: 🚀enhancement

#750 fix(vx-mock-data/cityTemperature): use better date format
  packages/vx-demo/src/sandboxes/vx-bargroup-horizontal/Example.tsx
  packages/vx-demo/src/sandboxes/vx-bargroup/Example.tsx
  packages/vx-demo/src/sandboxes/vx-barstack-horizontal/Example.tsx
  packages/vx-demo/src/sandboxes/vx-barstack/Example.tsx
  packages/vx-demo/src/sandboxes/vx-threshold/Example.tsx
  packages/vx-demo/src/sandboxes/vx-threshold/package.json
  packages/vx-mock-data/src/mocks/cityTemperature.ts
Labels: :boom: breaking changes, 🚀enhancement

#752 new(vx-axis): use numTicks when falling back on scale.domain
  packages/vx-axis/src/axis/Axis.tsx
Labels: 🚀enhancement

#754 new(vx-responsive): add leading option to resize debounce
  packages/vx-responsive/src/components/ParentSize.tsx
  packages/vx-responsive/src/enhancers/withParentSize.tsx
  packages/vx-responsive/src/enhancers/withScreenSize.tsx
Labels: 🚀enhancement

#756 new(vx-tooltip): add useTooltipInPortal
  packages/vx-demo/package.json
  packages/vx-demo/src/pages/docs/tooltip.tsx
  packages/vx-demo/src/sandboxes/vx-barstack/Example.tsx
  packages/vx-demo/src/sandboxes/vx-tooltip/Example.tsx
  packages/vx-demo/src/sandboxes/vx-tooltip/package.json
  packages/vx-tooltip/Readme.md
  packages/vx-tooltip/package.json
  packages/vx-tooltip/src/hooks/useTooltipInPortal.tsx
  packages/vx-tooltip/src/index.ts
  packages/vx-tooltip/src/tooltips/Tooltip.tsx
  packages/vx-tooltip/src/tooltips/TooltipWithBounds.tsx
  packages/vx-tooltip/test/useTooltip.test.tsx
  packages/vx-tooltip/test/useTooltipInPortal.test.tsx
  yarn.lock
Labels: :boom: breaking changes, 📝docs, 🚀enhancement

#755 new(vx-tooltip): add Portal + demo
  packages/vx-bounds/src/enhancers/withBoundingRects.tsx
  packages/vx-demo/src/components/Gallery/TooltipTile.tsx
  packages/vx-demo/src/components/Gallery/index.tsx
  packages/vx-demo/src/pages/docs/tooltip.tsx
  packages/vx-demo/src/pages/tooltip.tsx
  packages/vx-demo/src/sandboxes/vx-barstack/Example.tsx
  packages/vx-demo/src/sandboxes/vx-tooltip/Example.tsx
  packages/vx-demo/src/sandboxes/vx-tooltip/index.tsx
  packages/vx-demo/src/sandboxes/vx-tooltip/package.json
  packages/vx-demo/src/sandboxes/vx-tooltip/sandbox-styles.css
  packages/vx-tooltip/Readme.md
  packages/vx-tooltip/package.json
  packages/vx-tooltip/src/Portal.tsx
  packages/vx-tooltip/src/hooks/useTooltip.ts
  packages/vx-tooltip/src/hooks/useTooltipInPortal.tsx
  packages/vx-tooltip/src/index.ts
  packages/vx-tooltip/src/tooltips/Tooltip.tsx
  packages/vx-tooltip/src/tooltips/TooltipWithBounds.tsx
  packages/vx-tooltip/test/Portal.test.tsx
  packages/vx-tooltip/test/useTooltip.test.tsx
  packages/vx-tooltip/test/useTooltipInPortal.test.tsx
  yarn.lock
Labels: 🐯example, 📝docs, 🚀enhancement
