Repository airbnb/visx, pull requests merged in 2024-02, with the labels that each got.

#1796 internal: specify node js version
  .nvmrc
Labels: 🐛 bug, ✨ development, 🏠 internal

#1799 Adds to "in the wild", new site using visx/drag
  README.md
Labels: 📝 docs

#1800 docs: remove broken links from 'In the wild'
  README.md
Labels: 🐛 bug, 📝 docs
